# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-28 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pwhash',
            field=models.CharField(max_length=255),
        ),
    ]
