# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-31 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theWall', '0002_auto_20190131_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='userid',
        ),
    ]
