# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-27 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_available',
            new_name='numAvail',
        ),
    ]
